site_name: Scale Modelling
theme:
  name: material
  font:
    text: Roboto
  palette:
    scheme: slate
    primary: brown
    accent: deep-orange

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

