site_name: Scale Modelling
theme:
  name: material
  font:
    text: Roboto
  palette:
    scheme: slate
    primary: brown
    accent: deep-orange

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

